id: P2A818131
initial_creation_type: buddhism.ru
source_metadata:
  volume_no_to_title:
    '1': '''dul ba ''au'
    '2': '''dul ba bu'
    '3': '''dul ba du'
    '4': '''dul ba dzu'
    '5': '''dul ba lu'
    '6': '''dul ba mu'
    '7': '''dul ba nu 1'
    '8': '''dul ba nu'
    '9': '''dul ba phu'
    '10': '''dul ba pu'
    '11': '''dul ba ru'
    '12': '''dul ba shu'
    '13': '''dul ba su 1'
    '14': '''dul ba su'
    '15': '''dul ba tshu'
    '16': '''dul ba tsu'
    '17': '''dul ba wu'
    '18': '''dul ba yu'
    '19': '''dul ba zhu'
    '20': '''dul ba zu'
    '21': bzo rig ngo
    '22': rigs pa drug cu
    '23': rigs pa drug gi
    '24': gso rig he
    '25': gso rig kho
    '26': gso rig ko
    '27': sgra do ae
    '28': mdo 'grel bi
    '29': mdo 'grel chi
    '30': mdo 'grel ci
    '31': mdo 'grel di
    '32': mdo 'grel ji
    '33': mdo 'grel ngi
    '34': mdo 'grel ni
    '35': mdo 'grel nyi
    '36': mdo 'grel thi
    '37': mdo 'grel ti
    '38': mdo 'grel wi
    '39': mdon pa ai
    '40': mdon pa chu
    '41': mdon pa cu
    '42': mdon pa gu
    '43': mdon pa ju
    '44': mdon pa khu
    '45': mdon pa ku
    '46': mdon pa ngu
    '47': mdon pa nyu
    '48': mdon pa thu
    '49': mdon pa tu
    '50': seam ma 'ai
    '51': sems ma 'ai
    '52': sems ma bi
    '53': sems ma dzi
    '54': sems ma hi
    '55': sems ma li
    '56': sems ma mi
    '57': sems ma ri
    '58': sems ma tshi
    '59': sems ma tsi
    '60': sems ma wi
    '61': sems ma zhi
    '62': sems ma zi
    '63': sgra do le
    '64': sgra do re
    '65': sgra do se
    '66': sgra do she
    '67': shes phyin ba
    '68': shes phyin da
    '69': shes phyin ma
    '70': shes phyin na
    '71': shes phyin pa
    '72': shes phyin pha
    '73': shes phyin ta
    '74': shes phyin tha
    '75': skyes rabs au
    '76': skyes rabs ge 1
    '77': skyes rabs ge
    '78': skyes rabs hu
    '79': skyes rabs ke
    '80': skyes rabs khe
    '81': sna tshogs cho
    '82': sna tshogs co
    '83': sna tshogs do
    '84': sna tshogs jo
    '85': sna tshogs no
    '86': sna tshogs nyo
    '87': sna tshogs po
    '88': sna tshogs tho
    '89': sna tshogs to
    '90': spring yig nge
    '91': tshad ma 'ae
    '92': tshad ma be
    '93': tshad ma ce
    '94': tshad ma che
    '95': tshad ma de
    '96': tshad ma dze
    '97': tshad ma je
    '98': tshad ma me
    '99': tshad ma ne
    '100': tshad ma nye
    '101': tshad ma pe
    '102': tshad ma phe
    '103': tshad ma te
    '104': tshad ma the
    '105': tshad ma tse
    '106': tshad ma tshe
    '107': tshad ma we
    '108': tshad ma ye
    '109': tshad ma ze
    '110': tshad ma zhe
created_at: '2022-02-07T16:27:13.666649'
last_modified_at: '2022-02-07T16:27:13.666673'
